#!/usr/bin/env python3
"""Generate LONG1_REPORT.md for Phase Long-1 (4-arm x 10k, seed=42).

All four arms completed 10000 steps (verified: eval_curve has step=10000 row +
ckpt_step10000.pt + ckpt_final.pt). This script does NOT retrain anything; it
only reads the existing eval_curve.tsv files and the committed Round-2 5-arm
reference, then writes a markdown report.

Locked cross/structured/noisy schema is inherited verbatim from
scripts/summarize_round2_e3.py (the committed Round-2 E3 schema):
  cross      = mean over the 7 shared probe columns (NO distance_only column)
  structured = raster, hilbert, Bcov, rw_top4_eps0, rw_topk8
  noisy      = random, rw_eps015
The long run additionally evaluates val_distance_only_coverage; that column is
reported separately and is intentionally NOT folded into the locked aggregates.
"""
import csv
import math
from pathlib import Path

LONG_ROOT = Path('/home/admin/lyuyuhuan/order_lyu/probe_results_image_large/grw_e3ctrlsmall_round2_long10000_seed42')
REF_ROOT = Path('/home/admin/lyuyuhuan/order_lyu/probe_results_image_large/grw_e3ctrlsmall_round2_5arm')

ARMS = ['cont_random', 'cont_Bcov_balanced', 'cont_distance_only_coverage', 'cont_shuffled_Bcov_balanced']

# Locked Round-2 E3 schema (from summarize_round2_e3.py). 7 columns, NO dist.
CROSS7 = ['val_random', 'val_raster', 'val_hilbert', 'val_Bcov_balanced', 'val_rw_top4_eps0', 'val_rw_eps015', 'val_rw_topk8']
STRUCT = ['val_raster', 'val_hilbert', 'val_Bcov_balanced', 'val_rw_top4_eps0', 'val_rw_topk8']
NOISY = ['val_random', 'val_rw_eps015']
# Full endpoint columns (8) including the long-run-only dist probe.
ENDPOINT_COLS = ['val_random', 'val_raster', 'val_hilbert', 'val_Bcov_balanced',
                 'val_distance_only_coverage', 'val_rw_top4_eps0', 'val_rw_eps015', 'val_rw_topk8']

# Noise-floor proxy for classifying gaps. Single seed, max_eval_batches=16.
# This is an ESTIMATE, stated openly in the report; gaps below it are "within noise".
EPS_NEG = 0.002


def read_rows(root, arm):
    path = root / arm / 'eval_curve.tsv'
    if not path.exists():
        return None
    return list(csv.DictReader(path.open(), delimiter='\t'))


def row_at(rows, step):
    for r in rows:
        if int(r['step']) == step:
            return r
    return None


def fnum(x):
    return float(x)


def agg(row, cols):
    return sum(fnum(row[c]) for c in cols) / len(cols)


def md_table(headers, rows):
    out = ['| ' + ' | '.join(headers) + ' |', '|' + '|'.join(['---'] * len(headers)) + '|']
    for row in rows:
        vals = [f'{v:.4f}' if isinstance(v, float) else str(v) for v in row]
        out.append('| ' + ' | '.join(vals) + ' |')
    return '\n'.join(out)


def classify(g5, g10):
    d = g10 - g5
    if abs(g5) < EPS_NEG and abs(g10) < EPS_NEG:
        return 'converged*', d  # both within noise floor
    if (g5 > 0) != (g10 > 0) and abs(g10) >= EPS_NEG:
        return 'reversed', d
    if abs(g10) > abs(g5) + EPS_NEG:
        return 'expanded', d
    if abs(g10) < abs(g5) - EPS_NEG:
        return 'converged', d
    return 'persistent', d


def main():
    long_rows = {a: read_rows(LONG_ROOT, a) for a in ARMS}
    ref_rows = {a: read_rows(REF_ROOT, a) for a in ARMS}

    lines = []
    lines.append('# Phase Long-1 Report — 4-arm × 10k × seed=42')
    lines.append('')
    lines.append('Generated by `scripts/summarize_long1_e3.py` from existing eval_curve.tsv files. '
                 'No retraining performed. Lower val loss is better.')
    lines.append('')
    lines.append('**Run status:** all 4 arms completed step=10000 (master log: '
                 '`Phase Long-1 seed=42 max_steps=10000 finished 2026-05-21T19:43:07`). '
                 'Server disconnect occurred AFTER training finished; no OOM / killed / NaN / path error.')
    lines.append('')
    lines.append('**Locked schema (from `summarize_round2_e3.py`):** '
                 '`cross`=mean of 7 shared probes (no dist); '
                 '`structured`=raster/hilbert/Bcov/rw4/topk8; `noisy`=random/rw_eps015. '
                 'The long run additionally logs `val_distance_only_coverage`; it is reported '
                 'separately and NOT folded into the locked aggregates.')
    lines.append('')

    # ---- Table 1: 5k bit-match audit ----
    lines.append('## 1. 5k bit-match audit (long@5k vs committed Round-2 5arm@5k, seed=42)')
    lines.append('')
    lines.append('**Result: bit-match FAILED for every arm/column. This is EXPECTED, not a bug.** '
                 'Root cause: the cosine LR schedule in `train_imagelarge_round2.py:get_lr` is anchored to '
                 '`max_steps`. At step=5000 the long run has `lr=5.57e-05` (ratio=4900/9900=0.495) while the '
                 'committed 5k run has `lr=1.00e-05` (ratio=1.0, fully decayed). Both share the same step-0 '
                 'baseline ckpt and seed, but the LR trajectories diverge from step 1, so weights at step 5000 '
                 'differ. The master-log note "5k point should bit-match committed Round-2 seed=42" is therefore '
                 'invalid under the current max_steps-anchored schedule.')
    lines.append('')
    lines.append('Per-arm diff on the column intersection (long@5k − ref@5k):')
    lines.append('')
    bm_rows = []
    for a in ARMS:
        lr5 = row_at(long_rows[a], 5000)
        rr5 = row_at(ref_rows[a], 5000) if ref_rows[a] else None
        if rr5 is None:
            bm_rows.append([a, 'REF MISSING', '', '', ''])
            continue
        shared = [c for c in ENDPOINT_COLS if c in lr5 and c in rr5]
        maxabs = max(abs(fnum(lr5[c]) - fnum(rr5[c])) for c in shared)
        meanabs = sum(abs(fnum(lr5[c]) - fnum(rr5[c])) for c in shared) / len(shared)
        bm_rows.append([a, f"{lr5['lr']} vs {rr5['lr']}", f'{len(shared)}',
                        f'{meanabs:.4f}', f'{maxabs:.4f}'])
    lines.append(md_table(['arm', 'lr@5k (long vs ref)', 'shared_cols', 'mean|Δ|', 'max|Δ|'], bm_rows))
    lines.append('')
    lines.append('Note: ref arms `cont_random`/`cont_Bcov_balanced` have only 7 columns (no dist probe); '
                 '`cont_distance_only_coverage`/`cont_shuffled_Bcov_balanced` have 8. The eval protocol was not '
                 'uniform across the committed 5arm run either, so only the column intersection is compared.')
    lines.append('')

    # ---- Table 2: endpoint @10k ----
    lines.append('## 2. Endpoint eval @10k (all arms, all 8 probes)')
    lines.append('')
    ep_rows = []
    for a in ARMS:
        r = row_at(long_rows[a], 10000)
        ep_rows.append([a] + [fnum(r[c]) for c in ENDPOINT_COLS])
    short = ['random', 'raster', 'hilbert', 'Bcov', 'dist', 'rw4', 'eps', 'topk8']
    lines.append(md_table(['arm'] + short, ep_rows))
    lines.append('')
    lines.append('Delta vs cont_random @10k:')
    lines.append('')
    base10 = row_at(long_rows['cont_random'], 10000)
    d_rows = []
    for a in ARMS:
        if a == 'cont_random':
            continue
        r = row_at(long_rows[a], 10000)
        d_rows.append([a] + [fnum(r[c]) - fnum(base10[c]) for c in ENDPOINT_COLS])
    lines.append(md_table(['arm'] + short, d_rows))
    lines.append('')

    # ---- Table 3: curve summary ----
    lines.append('## 3. Curve summary — cross/structured/noisy aggregates over steps')
    lines.append('')
    for a in ARMS:
        lines.append(f'### {a}')
        lines.append('')
        crows = []
        for r in long_rows[a]:
            step = int(r['step'])
            if step == 0:
                continue
            crows.append([step, agg(r, CROSS7), agg(r, STRUCT), agg(r, NOISY),
                          fnum(r['val_distance_only_coverage'])])
        lines.append(md_table(['step', 'cross_avg', 'structured_avg', 'noisy_avg', 'dist(sep)'], crows))
        lines.append('')

    # ---- Table 4: gap table ----
    lines.append('## 4. Gap table (arm-vs-arm aggregate gaps; negative = first arm lower=better)')
    lines.append('')
    comparisons = [
        ('Bcov - distance', 'cont_Bcov_balanced', 'cont_distance_only_coverage'),
        ('Bcov - shuffled', 'cont_Bcov_balanced', 'cont_shuffled_Bcov_balanced'),
    ]
    metric_cols = [('cross', CROSS7), ('structured', STRUCT), ('noisy', NOISY)]
    gap_rows = []
    classif = {}
    for name, a1, a2 in comparisons:
        for mname, mcols in metric_cols:
            r1_5, r2_5 = row_at(long_rows[a1], 5000), row_at(long_rows[a2], 5000)
            r1_10, r2_10 = row_at(long_rows[a1], 10000), row_at(long_rows[a2], 10000)
            g5 = agg(r1_5, mcols) - agg(r2_5, mcols)
            g10 = agg(r1_10, mcols) - agg(r2_10, mcols)
            verdict, d = classify(g5, g10)
            classif[(name, mname)] = (g5, g10, d, verdict)
            gap_rows.append([name, mname, g5, g10, d, verdict])
    lines.append(md_table(['comparison', 'metric', '@5k', '@10k', 'delta(10k-5k)', 'verdict'], gap_rows))
    lines.append('')
    lines.append(f'Verdict thresholds (EPS_NEG={EPS_NEG}, a single-seed eval-noise proxy): '
                 '`reversed`=sign flip with |@10k|≥EPS; `expanded`=|gap| grows by >EPS; '
                 '`converged`=|gap| shrinks by >EPS; `converged*`=both endpoints within noise floor; '
                 '`persistent`=same sign, comparable magnitude.')
    lines.append('')

    # ---- Table 5: conclusion ----
    lines.append('## 5. Conclusion (locked schema: persistent / expanded / converged / reversed)')
    lines.append('')
    for (name, mname), (g5, g10, d, verdict) in classif.items():
        lines.append(f'- **{name} / {mname}**: @5k={g5:+.4f} → @10k={g10:+.4f} (Δ={d:+.4f}) → **{verdict}**')
    lines.append('')
    lines.append('### Caveats (mandatory)')
    lines.append('- **Single seed (42).** No cross-seed CI; all gaps below must be read against seed noise.')
    lines.append('- **Eval uses max_eval_batches=16** per probe — gaps at the 1e-3 level are at/near the noise floor.')
    lines.append('- The 5k→10k comparison is **internally consistent** (same training trajectory), unlike the '
                 'cross-run 5k bit-match, which is invalidated by the max_steps-anchored LR schedule (Table 1).')
    lines.append('')

    report = LONG_ROOT / 'LONG1_REPORT.md'
    report.write_text('\n'.join(lines) + '\n')
    print(report)


if __name__ == '__main__':
    main()
